/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#13677b",
        "primary-container": "#005f73",
        "tertiary-fixed-dim": "#fcb97b",
        "on-tertiary-fixed": "#2d1600",
        "on-secondary": "#ffffff",
        "primary-fixed": "#b2ebff",
        "tertiary-fixed": "#ffdcc0",
        "on-error-container": "#93000a",
        "secondary-fixed": "#e4e2de",
        "inverse-on-surface": "#f3f0f0",
        "surface-bright": "#fbf9f8",
        "on-primary-fixed": "#001f27",
        "on-primary-container": "#91d7ee",
        "error": "#ba1a1a",
        "primary": "#004655",
        "on-background": "#1b1c1c",
        "outline-variant": "#bfc8cc",
        "inverse-primary": "#8bd1e8",
        "on-surface-variant": "#3f484c",
        "tertiary": "#603401",
        "inverse-surface": "#303030",
        "secondary-fixed-dim": "#c8c6c3",
        "on-error": "#ffffff",
        "surface-variant": "#e4e2e1",
        "secondary-container": "#e1dfdc",
        "surface-container-low": "#f6f3f2",
        "surface-dim": "#dcd9d9",
        "background": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1c1c",
        "on-tertiary-fixed-variant": "#693c07",
        "outline": "#6f797c",
        "on-secondary-fixed-variant": "#474744",
        "surface-container": "#f0eded",
        "secondary": "#5e5e5c",
        "on-tertiary-container": "#ffbf86",
        "error-container": "#ffdad6",
        "surface": "#fbf9f8",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#7c4b17",
        "surface-container-high": "#eae8e7",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#004e5f",
        "on-secondary-fixed": "#1b1c1a",
        "on-secondary-container": "#636360",
        "surface-container-highest": "#e4e2e1",
        "primary-fixed-dim": "#8bd1e8"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "margin-mobile": "20px",
        "section-padding": "120px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "unit": "8px"
      },
      fontFamily: {
        "headline-lg": ["Noto Serif", "serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Noto Serif", "serif"],
        "headline-md": ["Noto Serif", "serif"],
        "headline-lg-mobile": ["Noto Serif", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
