import os

base_dir = r'c:\Users\DELL\Documents\azulsurf-morocco\frontend\src\pages\admin'

replacements = {
    'AdminPackages.jsx': {
        "'Impossible de charger les packages. Veuillez réessayer.'": "t('adminPackages.fetchError')",
        "\"L'image est trop volumineuse. Taille maximale autorisée: 2 Mo.\"": "t('adminPackages.sizeError')",
        "'Veuillez renseigner au moins un titre (FR ou EN).'": "t('adminPackages.titleRequired')",
        "'Veuillez saisir un prix valide supérieur ou égal à 0.'": "t('adminPackages.priceRequired')",
        "'Package mis à jour avec succès.'": "t('adminPackages.updateSuccess')",
        "'Package créé avec succès.'": "t('adminPackages.createSuccess')",
        "\"Une erreur est survenue lors de l'enregistrement.\"": "t('adminPackages.submitError')",
        "'Package supprimé avec succès.'": "t('adminPackages.deleteSuccess')",
        "'Erreur lors de la suppression du package.'": "t('adminPackages.deleteError')",
        ">Gestion des Packages<": ">{t('adminPackages.title')}<",
        ">Créez et modifiez les formules tout-inclus d'Azul Surf.<": ">{t('adminPackages.subtitle')}<",
        ">Ajouter un Package<": ">{t('adminPackages.addPackage')}<",
        "Packages disponibles (": "{t('adminPackages.availablePackages')} (",
        ">CMS Actif<": ">{t('adminPackages.activeCms')}<",
        ">Chargement des packages...<": ">{t('adminPackages.loading')}<",
        "Aucun package configuré. Cliquez sur \"Ajouter un Package\" pour commencer.": "{t('adminPackages.emptyState')}",
        ">Image<": ">{t('adminPackages.colImage')}<",
        ">Titre / Description<": ">{t('adminPackages.colTitle')}<",
        ">Durée<": ">{t('adminPackages.colDuration')}<",
        ">Prix<": ">{t('adminPackages.colPrice')}<",
        ">Statut<": ">{t('adminPackages.colStatus')}<",
        ">Actions<": ">{t('adminPackages.colActions')}<",
        "pkg.is_active ? 'Actif' : 'Inactif'": "pkg.is_active ? t('adminPackages.statusActive') : t('adminPackages.statusInactive')",
        "selectedPackage ? 'Modifier le Surf Package' : 'Créer un Surf Package'": "selectedPackage ? t('adminPackages.editPackage') : t('adminPackages.createPackageTitle')",
        ">Nouvelle offre Azul Surf<": ">{t('adminPackages.newOffer')}<",
        ">Contenu Français (FR)<": ">{t('adminPackages.langFr')}<",
        ">Contenu Anglais (EN)<": ">{t('adminPackages.langEn')}<",
        ">Titre du Package (FR)<": ">{t('adminPackages.titleFr')}<",
        "placeholder=\"Ex: Package Surf & Yoga Tout-Inclus\"": "placeholder={t('adminPackages.titleFrPlaceholder')}",
        ">Description (FR)<": ">{t('adminPackages.descFr')}<",
        "placeholder=\"Décrivez l'offre, l'ambiance, l'hébergement, la restauration...\"": "placeholder={t('adminPackages.descFrPlaceholder')}",
        ">Package Title (EN)<": ">{t('adminPackages.titleEn')}<",
        "placeholder=\"Ex: All-Inclusive Surf & Yoga Package\"": "placeholder={t('adminPackages.titleEnPlaceholder')}",
        ">Description (EN)<": ">{t('adminPackages.descEn')}<",
        "placeholder=\"Describe the offer, details, villa experience, meals...\"": "placeholder={t('adminPackages.descEnPlaceholder')}",
        ">Durée (ex: 7 jours / 6 nuits)<": ">{t('adminPackages.duration')}<",
        "placeholder=\"Ex: 7 jours / 6 nuits\"": "placeholder={t('adminPackages.durationPlaceholder')}",
        ">Tarif (EUR €)<": ">{t('adminPackages.price')}<",
        "placeholder=\"Ex: 850\"": "placeholder={t('adminPackages.pricePlaceholder')}",
        ">Image du Package<": ">{t('adminPackages.packageImage')}<",
        ">Changer d'image<": ">{t('adminPackages.changeImage')}<",
        ">Glissez une image ou cliquez pour téléverser<": ">{t('adminPackages.uploadImage')}<",
        ">JPEG, PNG ou WEBP (Max 2 Mo)<": ">{t('adminPackages.imageSize')}<",
        ">Statut Actif<": ">{t('adminPackages.statusActiveToggle')}<",
        ">Rendre visible sur le site public<": ">{t('adminPackages.statusVisible')}<",
        ">Services Inclus<": ">{t('adminPackages.includedServices')}<",
        ">Ajouter une ligne<": ">{t('adminPackages.addRow')}<",
        "placeholder=\"Ex: Coaching certifié ISA quotidien\"": "placeholder={t('adminPackages.servicePlaceholder')}",
        ">Annuler<": ">{t('adminPackages.cancel')}<",
        ">Enregistrement...<": ">{t('adminPackages.saving')}<",
        ">Enregistrer le Package<": ">{t('adminPackages.savePackage')}<",
        ">Supprimer ce Surf Package ?<": ">{t('adminPackages.deleteConfirmTitle')}<",
        "Êtes-vous sûr de vouloir supprimer le package": "{t('adminPackages.deleteConfirmDesc')}",
        "? Cette action est irréversible.": "? {t('adminPackages.deleteConfirmWarning')}",
        ">Supprimer définitivement<": ">{t('adminPackages.deletePermanently')}<",
        "'Titre non défini'": "t('adminPackages.untitled')",
        "'Aucune description'": "t('adminPackages.noDescription')",
    },
    'AdminGallery.jsx': {
        "'Impossible de charger la galerie. Veuillez réessayer.'": "t('adminGallery.fetchError')",
        "\"L'image est trop volumineuse. Taille maximale autorisée: 2 Mo.\"": "t('adminGallery.sizeError')",
        "'Veuillez sélectionner une image à téléverser.'": "t('adminGallery.imageRequired')",
        "'Image mise à jour avec succès.'": "t('adminGallery.updateSuccess')",
        "'Image ajoutée à la galerie.'": "t('adminGallery.createSuccess')",
        "\"Une erreur est survenue lors de l'enregistrement.\"": "t('adminGallery.submitError')",
        "'Image supprimée de la galerie.'": "t('adminGallery.deleteSuccess')",
        "'Erreur lors de la suppression.'": "t('adminGallery.deleteError')",
        ">Galerie Photos<": ">{t('adminGallery.title')}<",
        ">Gérez les visuels affichés dans la galerie publique d'Azul Surf.<": ">{t('adminGallery.subtitle')}<",
        ">Ajouter une Photo<": ">{t('adminGallery.addPhoto')}<",
        "Filtrer:": "{t('adminGallery.filter')}",
        "Toutes (": "{t('adminGallery.all')} (",
        ">Chargement des photos...<": ">{t('adminGallery.loading')}<",
        ">Aucune photo trouvée pour cette catégorie.<": ">{t('adminGallery.emptyState')}<",
        ">Inactif<": ">{t('adminGallery.inactive')}<",
        "'Sans titre'": "t('adminGallery.untitled')",
        "Ajouté le ": "{t('adminGallery.addedOn')} ",
        "selectedItem ? 'Modifier la Photo' : 'Ajouter une Photo'": "selectedItem ? t('adminGallery.editPhoto') : t('adminGallery.addPhoto')",
        ">Nouveau visuel Azul Surf<": ">{t('adminGallery.newVisual')}<",
        ">Titre Français<": ">{t('adminGallery.langFr')}<",
        ">English Title<": ">{t('adminGallery.langEn')}<",
        ">Titre / Légende (Optionnel - FR)<": ">{t('adminGallery.titleFr')}<",
        "placeholder=\"Ex: Session coucher de soleil sur la plage\"": "placeholder={t('adminGallery.titleFrPlaceholder')}",
        ">Title / Legend (Optional - EN)<": ">{t('adminGallery.titleEn')}<",
        "placeholder=\"Ex: Sunset surf session on the beach\"": "placeholder={t('adminGallery.titleEnPlaceholder')}",
        ">Catégorie<": ">{t('adminGallery.category')}<",
        ">Surf<": ">{t('adminGallery.catSurf')}<",
        ">Camp (Hébergement & Ambiance)<": ">{t('adminGallery.catCamp')}<",
        ">Activities (Yoga, Détente)<": ">{t('adminGallery.catActivities')}<",
        ">Trips (Excursions)<": ">{t('adminGallery.catTrips')}<",
        ">Food (Plats Marocains)<": ">{t('adminGallery.catFood')}<",
        ">Image<": ">{t('adminGallery.image')}<",
        ">Changer d'image<": ">{t('adminGallery.changeImage')}<",
        ">Sélectionner une photo<": ">{t('adminGallery.selectPhoto')}<",
        ">Visible en public<": ">{t('adminGallery.visiblePublic')}<",
        ">Afficher dans la galerie<": ">{t('adminGallery.showInGallery')}<",
        ">Annuler<": ">{t('adminGallery.cancel')}<",
        ">Enreg...<": ">{t('adminGallery.saving')}<",
        ">Enregistrer<": ">{t('adminGallery.save')}<",
        ">Supprimer de la Galerie ?<": ">{t('adminGallery.deleteConfirmTitle')}<",
        ">Voulez-vous vraiment supprimer définitivement cette photo de votre galerie ?<": ">{t('adminGallery.deleteConfirmDesc')}<",
        ">Supprimer<": ">{t('adminGallery.delete')}<",
    },
    'AdminReviews.jsx': {
        "'Impossible de charger les avis. Veuillez réessayer.'": "t('adminReviews.fetchError')",
        "'Le nom du client est requis.'": "t('adminReviews.nameRequired')",
        "\"Le texte de l'avis est requis.\"": "t('adminReviews.textRequired')",
        "'Avis mis à jour avec succès.'": "t('adminReviews.updateSuccess')",
        "'Avis créé avec succès.'": "t('adminReviews.createSuccess')",
        "\"Une erreur est survenue lors de l'enregistrement.\"": "t('adminReviews.submitError')",
        "\"Statut d'approbation mis à jour.\"": "t('adminReviews.approvalSuccess')",
        "'Erreur lors de la modification du statut.'": "t('adminReviews.approvalError')",
        "'Avis supprimé définitivement.'": "t('adminReviews.deleteSuccess')",
        "\"Erreur lors de la suppression de l'avis.\"": "t('adminReviews.deleteError')",
        ">Modération des Avis Clients<": ">{t('adminReviews.title')}<",
        ">Validez et publiez les témoignages reçus sur la page d'accueil.<": ">{t('adminReviews.subtitle')}<",
        ">Ajouter un Témoignage<": ">{t('adminReviews.addReview')}<",
        "Témoignages recueillis (": "{t('adminReviews.collectedReviews')} (",
        ">CMS Actif<": ">{t('adminReviews.activeCms')}<",
        ">Chargement des avis...<": ">{t('adminReviews.loading')}<",
        ">Aucun avis trouvé. Ajoutez-en un manuellement pour commencer.<": ">{t('adminReviews.emptyState')}<",
        ">Client<": ">{t('adminReviews.colClient')}<",
        ">Note<": ">{t('adminReviews.colRating')}<",
        ">Message de l'avis<": ">{t('adminReviews.colMessage')}<",
        ">Approuvé<": ">{t('adminReviews.colApproved')}<",
        ">Visibilité<": ">{t('adminReviews.colVisibility')}<",
        ">Actions<": ">{t('adminReviews.colActions')}<",
        "review.is_approved ? 'Oui' : 'En attente'": "review.is_approved ? t('adminReviews.yes') : t('adminReviews.pending')",
        "review.is_active ? 'Actif' : 'Masqué'": "review.is_active ? t('adminReviews.active') : t('adminReviews.hidden')",
        "selectedReview ? 'Modifier le Témoignage' : 'Créer un Témoignage'": "selectedReview ? t('adminReviews.editReview') : t('adminReviews.createReview')",
        ">Avis client Azul Surf<": ">{t('adminReviews.clientReview')}<",
        ">Nom du Client<": ">{t('adminReviews.clientName')}<",
        "placeholder=\"Ex: Elena Rossi\"": "placeholder={t('adminReviews.clientNamePlaceholder')}",
        ">Note (Étoiles 1-5)<": ">{t('adminReviews.rating')}<",
        ">5 Étoiles (Excellent)<": ">{t('adminReviews.stars5')}<",
        ">4 Étoiles (Très bon)<": ">{t('adminReviews.stars4')}<",
        ">3 Étoiles (Moyen)<": ">{t('adminReviews.stars3')}<",
        ">2 Étoiles (Médiocre)<": ">{t('adminReviews.stars2')}<",
        ">1 Étoile (Mauvais)<": ">{t('adminReviews.stars1')}<",
        ">Message de l'Avis<": ">{t('adminReviews.reviewMessage')}<",
        "placeholder=\"Contenu du témoignage du client...\"": "placeholder={t('adminReviews.reviewMessagePlaceholder')}",
        ">Valider pour publication<": ">{t('adminReviews.validatePublish')}<",
        ">Visible sur le site<": ">{t('adminReviews.visibleSite')}<",
        ">Annuler<": ">{t('adminReviews.cancel')}<",
        ">Enreg...<": ">{t('adminReviews.saving')}<",
        ">Enregistrer<": ">{t('adminReviews.save')}<",
        ">Supprimer cet avis ?<": ">{t('adminReviews.deleteConfirmTitle')}<",
        "Voulez-vous vraiment supprimer définitivement le témoignage de ": "{t('adminReviews.deleteConfirmDesc')} ",
        " ? cette action est irréversible.": " ? {t('adminReviews.deleteConfirmWarning')}",
        ">Supprimer<": ">{t('adminReviews.delete')}<",
    },
    'AdminMessages.jsx': {
        "'Impossible de charger les messages. Veuillez réessayer.'": "t('adminMessages.fetchError')",
        "'Erreur lors du chargement des détails du message.'": "t('adminMessages.detailError')",
        "'Message supprimé avec succès.'": "t('adminMessages.deleteSuccess')",
        "'Erreur lors de la suppression du message.'": "t('adminMessages.deleteError')",
        ">Messages de Contact<": ">{t('adminMessages.title')}<",
        ">Lisez et gérez les demandes d'informations reçues via le formulaire du site.<": ">{t('adminMessages.subtitle')}<",
        ">Actualiser<": ">{t('adminMessages.refresh')}<",
        "Boîte de réception (": "{t('adminMessages.inbox')} (",
        ">Boîte active<": ">{t('adminMessages.activeInbox')}<",
        ">Chargement de la boîte de réception...<": ">{t('adminMessages.loading')}<",
        ">Aucun message de contact reçu.<": ">{t('adminMessages.emptyState')}<",
        ">Statut<": ">{t('adminMessages.colStatus')}<",
        ">Expéditeur<": ">{t('adminMessages.colSender')}<",
        ">Sujet / Intérêt<": ">{t('adminMessages.colSubject')}<",
        ">Date de réception<": ">{t('adminMessages.colDate')}<",
        ">Actions<": ">{t('adminMessages.colActions')}<",
        "msg.is_read ? 'Lu' : 'Non lu'": "msg.is_read ? t('adminMessages.read') : t('adminMessages.unread')",
        "msg.subject || 'Aucun objet'": "msg.subject || t('adminMessages.noSubject')",
        "Intérêt: ": "{t('adminMessages.interest')} ",
        "title=\"Lire le message\"": "title={t('adminMessages.readMessage')}",
        "title=\"Supprimer\"": "title={t('adminMessages.delete')}",
        ">Lecture du Message<": ">{t('adminMessages.readingMessage')}<",
        "Date: ": "{t('adminMessages.date')} ",
        ">Service d'intérêt:<": ">{t('adminMessages.serviceInterest')}<",
        ">Sujet<": ">{t('adminMessages.subject')}<",
        ">Message<": ">{t('adminMessages.message')}<",
        ">Supprimer ce message<": ">{t('adminMessages.deleteThisMessage')}<",
        ">Fermer<": ">{t('adminMessages.close')}<",
        ">Supprimer le Message ?<": ">{t('adminMessages.deleteConfirmTitle')}<",
        "Voulez-vous vraiment supprimer définitivement ce message de ": "{t('adminMessages.deleteConfirmDesc')} ",
        " ? cette action est irréversible.": " ? {t('adminMessages.deleteConfirmWarning')}",
    }
}

for filename, reps in replacements.items():
    file_path = os.path.join(base_dir, filename)
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for old, new in reps.items():
        content = content.replace(old, new)
        
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

print('Updated component files')
